// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/maket12/SubTrack/internal/domain/entity"
	filter "github.com/maket12/SubTrack/internal/domain/filter"

	mock "github.com/stretchr/testify/mock"
)

// SubscriptionRepository is an autogenerated mock type for the SubscriptionRepository type
type SubscriptionRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, s
func (_m *SubscriptionRepository) Create(ctx context.Context, s *entity.Subscription) (int, error) {
	ret := _m.Called(ctx, s)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 int
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Subscription) int); ok {
		r0 = rf(ctx, s)
	} else {
		r0 = ret.Int(0)
	}

	var r1 error
	if len(ret) > 1 {
		if rf, ok := ret.Get(1).(func(context.Context, *entity.Subscription) error); ok {
			r1 = rf(ctx, s)
		} else {
			r1 = ret.Error(1)
		}
	}

	return r0, r1
}

// Delete provides a mock function with given fields: ctx, id
func (_m *SubscriptionRepository) Delete(ctx context.Context, id int) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Get provides a mock function with given fields: ctx, id
func (_m *SubscriptionRepository) Get(ctx context.Context, id int) (*entity.Subscription, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *entity.Subscription
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (*entity.Subscription, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) *entity.Subscription); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Subscription)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetList provides a mock function with given fields: ctx, _a1
func (_m *SubscriptionRepository) GetList(ctx context.Context, _a1 filter.ListFilter) ([]entity.Subscription, error) {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for GetList")
	}

	var r0 []entity.Subscription
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, filter.ListFilter) ([]entity.Subscription, error)); ok {
		return rf(ctx, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, filter.ListFilter) []entity.Subscription); ok {
		r0 = rf(ctx, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Subscription)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, filter.ListFilter) error); ok {
		r1 = rf(ctx, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTotalSum provides a mock function with given fields: ctx, _a1
func (_m *SubscriptionRepository) GetTotalSum(ctx context.Context, _a1 filter.SumFilter) (int, error) {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for GetTotalSum")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, filter.SumFilter) (int, error)); ok {
		return rf(ctx, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, filter.SumFilter) int); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, filter.SumFilter) error); ok {
		r1 = rf(ctx, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, s
func (_m *SubscriptionRepository) Update(ctx context.Context, s *entity.Subscription) error {
	ret := _m.Called(ctx, s)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Subscription) error); ok {
		r0 = rf(ctx, s)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewSubscriptionRepository creates a new instance of SubscriptionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSubscriptionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *SubscriptionRepository {
	mock := &SubscriptionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
